### ISSUE TITLE
error: RangeError: : invalid name

### ISSUE THREAD

**Issue by niqbert** [ebaauw/homebridge-soma#18]
Hello,

one of my Somas has been broken today. So I removed it from the Smart Shades App, but the broken device is not removed from the Home App and in Homebridge I get following error:

[04/03/2022, 19:34:14] [SOMA] error: d003f2a53e25: RangeError: : invalid name
    at SomaAccessory.set name (/usr/local/lib/node_modules/homebridge-soma/node_modules/homebridge-lib/lib/Delegate.js:108:13)
    at SomaAccessory.set name [as name] (/usr/local/lib/node_modules/homebridge-soma/node_modules/homebridge-lib/lib/AccessoryDelegate.js:132:16)
    at SomaAccessory.onDeviceFound (/usr/local/lib/node_modules/homebridge-soma/lib/SomaAccessory.js:66:15)
    at SomaClient.<anonymous> (/usr/local/lib/node_modules/homebridge-soma/lib/SomaPlatform.js:161:40)
    at SomaClient.emit (node:events:520:28)
    at SomaClient.emit (/usr/local/lib/node_modules/homebridge-soma/lib/BleClient.js:111:13)
    at SomaClient.<anonymous> (/usr/local/lib/node_modules/homebridge-soma/lib/SomaClient.js:400:14)
    at SomaClient.emit (node:events:520:28)
    at SomaClient.emit (/usr/local/lib/node_modules/homebridge-soma/lib/BleClient.js:111:13)
    at Noble.<anonymous> (/usr/local/lib/node_modules/homebridge-soma/lib/BleClient.js:239:18)

What can I do? :(

**Comment by ebaauw** [comment]
As long as it’s within BLE range and powered, Homebridge SOMA will discover it.  You could use a whitelist to expose only the devices you want (see #4), but I’m not sure if that’ll prevent the RangeError, cause by the shade not having a name.

**Comment by niqbert** [comment]
Thanks. With the whiteliste it works fine.
